# Generated by Django 2.1.5 on 2019-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
