# Generated by Django 2.1.5 on 2019-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190118_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
