# Generated by Django 2.1.5 on 2019-01-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190125_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default='5e80bc51-de26-42ad-b2de-7018d2c3a0ee', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='5261bcf8-0dcc-4139-b903-516e50816094', editable=False, primary_key=True, serialize=False),
        ),
    ]
