# Generated by Django 2.1.5 on 2019-01-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190130_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default='5ec38fd0-6b4f-43b1-8c7a-fc865ebcd235', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='60c5b098-079a-4c3b-963e-7a68154a6e39', editable=False, primary_key=True, serialize=False),
        ),
    ]
